version: "3"
services:
  web:
    image: "gpt-fe:gptneo_v1"
    user: "root"
    working_dir: /home/node/app
    ports:
      - 8080:8080
    environment:
      HOST: 0.0.0.0
      PORT: 8080
    command: "npm run dev"
